export {
  ContractValidationError,
  type CodeEdge,
  type CodeIntelligenceProvider,
  type CodeNode,
  type Completeness,
  type ConformanceExpectation,
  type ConformanceReport,
  type NeighborhoodFound,
  type NeighborhoodQuery,
  type NeighborhoodResult,
  type QueryValidation,
  type RepositoryIdentity,
  type RepositoryMap,
  type RepositoryMapResult,
  type EvidenceKind,
  type RepositoryBoundary,
  type RepositoryEntryPoint,
  type RepositoryLanguage,
  type RepositoryOverview,
  type RepositoryOverviewResult,
  type SourceReference,
  type SnapshotIdentity,
  type SourceLocation,
  type TaskContextConformanceExpectation,
  type TaskContextConformanceReport,
  type TaskContextFound,
  type TaskContextFocus,
  type TaskContextProvider,
  type TaskContextQuery,
  type TaskContextResult,
  type TaskEvidenceFact,
} from "./contract.ts";
export { evaluateConformance, evaluateTaskContextConformance } from "./conformance.ts";
export {
  normalizeNeighborhood,
  normalizeRepositoryMap,
  normalizeRepositoryOverview,
  normalizeTaskContext,
  stableSerialize,
  validateNeighborhoodQuery,
  validateTaskContextQuery,
} from "./normalize.ts";
