import { defineSchema, type OkfConceptSchema } from "./schema-definition-builder.ts";
import { INFRASTRUCTURE_SCHEMAS } from "./schema-infrastructure-definitions.ts";

export type { OkfConceptSchema } from "./schema-definition-builder.ts";

export const OKF_CONCEPT_SCHEMAS: readonly OkfConceptSchema[] = [
  defineSchema(
    "Repository",
    "Source repository identity, responsibility and navigation root",
    "repositories/<repository>/repository.md",
    10,
    ["repository", "source root"],
    ["admitted repository identity"],
    ["# Purpose", "# Structure", "# Entry Points"],
    ["Service", "Server", "API Endpoint", "Business Flow"],
  ),
  defineSchema(
    "Service",
    "A deployable or independently owned software service",
    "repositories/<repository>/services/<slug>.md",
    30,
    ["service", "microservice", "application"],
    ["service boundary or deployment identity"],
    ["# Responsibility", "# Interfaces", "# Dependencies"],
    ["Repository", "Server", "API Endpoint", "Event", "Database Table", "Queue", "Business Flow"],
  ),
  defineSchema(
    "Server",
    "A long-running network server or application process",
    "repositories/<repository>/servers/<slug>.md",
    40,
    ["server", "listener", "http server", "grpc server"],
    ["server entry point or listener evidence"],
    ["# Runtime", "# Interfaces", "# Operations"],
    ["Repository", "Service", "API Endpoint", "Database Table", "Queue"],
  ),
  defineSchema(
    "API Endpoint",
    "One externally callable HTTP, RPC or command endpoint",
    "repositories/<repository>/api/<slug>.md",
    50,
    ["api endpoint", "http route", "rpc method", "route"],
    ["method/protocol and handler evidence"],
    ["# Contract", "# Handler", "# Failure Behavior"],
    ["Service", "Server", "Business Flow", "Event"],
    {
      investigationQuestions: [
        "What method and route are exposed?", "Which concrete handler receives the request?",
        "Which caller or client uses this endpoint?",
      ],
      metadataGuidance: [
        { field: "method", evidence: "route or infrastructure declaration", requiredWhenSupported: true },
        { field: "route", evidence: "route or client call", requiredWhenSupported: true },
        { field: "handler", evidence: "route-to-handler declaration", requiredWhenSupported: true },
      ],
      relationshipGuidance: [{ kind: "handled-by", targetTypes: ["Service", "AWS Lambda", "Server"], evidence: "route declaration resolving the handler" }],
    },
  ),
  defineSchema(
    "Event",
    "A named event produced or consumed by a system",
    "repositories/<repository>/events/<slug>.md",
    40,
    ["event", "event type", "message"],
    ["event name and producer or consumer evidence"],
    ["# Meaning", "# Producers", "# Consumers"],
    ["Service", "Queue", "AWS SQS Queue", "Business Flow"],
    {
      investigationQuestions: ["What produces this event?", "What consumes it?", "What schedule or event pattern triggers it?"],
      metadataGuidance: [{ field: "trigger", evidence: "schedule, event pattern or producer call", requiredWhenSupported: true }],
      relationshipGuidance: [{ kind: "triggers", targetTypes: ["AWS Lambda", "Service", "Business Flow"], evidence: "event target or consumer binding" }],
    },
  ),
  defineSchema(
    "Database Table",
    "A concrete relational or logical database table",
    "repositories/<repository>/data/tables/<slug>.md",
    60,
    ["database table", "sql table", "table"],
    ["table identity or schema evidence"],
    ["# Data", "# Ownership", "# Access"],
    ["Service", "Server", "Business Flow"],
    {
      investigationQuestions: ["What is the table identity and key/schema?", "Which runtime reads or writes it?", "How is its name passed to the runtime?"],
      metadataGuidance: [
        { field: "resource_name", evidence: "infrastructure or schema declaration", requiredWhenSupported: true },
        { field: "keys", evidence: "table schema declaration", requiredWhenSupported: false },
      ],
      relationshipGuidance: [{
        kind: "accessed-by", targetTypes: ["AWS Lambda", "Service", "Server"],
        evidence: "runtime database operation plus configuration binding",
      }],
    },
  ),
  defineSchema(
    "Queue",
    "A generic asynchronous queue with known producer or consumer",
    "repositories/<repository>/queues/<slug>.md",
    30,
    ["queue", "message queue"],
    ["queue identity", "producer or consumer evidence"],
    ["# Messages", "# Producers", "# Consumers"],
    ["Service", "Event", "Business Flow"],
  ),
  ...INFRASTRUCTURE_SCHEMAS,
  defineSchema(
    "Cross-Repository Relationship",
    "An evidence-bearing relationship between concepts owned by different repositories",
    "relationships/<slug>.md",
    70,
    ["cross-repository", "cross repo", "producer consumer", "repository relationship"],
    ["source endpoint", "target endpoint", "relationship evidence"],
    ["# Source", "# Relationship", "# Target", "# Evidence and Limitations"],
    ["Repository", "Service", "API Endpoint", "Event", "AWS Lambda", "AWS SQS Queue", "Business Flow"],
  ),
  defineSchema(
    "Open Question",
    "A visible uncertainty requiring evidence or owner input",
    "repositories/<repository>/questions/<slug>.md",
    10,
    ["question", "uncertain", "unknown", "conflict"],
    ["specific unresolved question"],
    ["# Question", "# Why It Matters", "# Evidence Needed"],
    ["Repository", "Service", "Business Flow"],
  ),
  defineSchema(
    "Maintainer Guidance",
    "Durable human correction, defer or authoring instruction",
    "repositories/<repository>/guidance/<slug>.md",
    10,
    ["maintainer guidance", "correction", "defer", "reopen"],
    ["explicit maintainer instruction"],
    ["# Guidance", "# Scope"],
    ["Open Question", "Repository", "Service", "Business Flow"],
    { requiredFrontmatter: ["title", "description", "generated"] },
  ),
];
