export const HUB_README_PATH = "README.md" as const;

export function renderHubReadme(): string {
  return "# AgentBase-Hub\n\n"
    + "AgentBase-Hub is a human-readable OKF knowledge repository created and managed by "
    + "[AgentBase-MCP](https://github.com/khoaha1904/AgentBase-MCP). "
    + "Return to this Hub's [repository root](.).\n\n"
    + "## Start here\n\n"
    + "Open [`index.md`](index.md). It is the canonical progressive-disclosure entrypoint "
    + "for both people and agents. Follow its direct Domain or Repository entrypoints, then "
    + "their links to useful concepts instead of scanning every file.\n\n"
    + "## What this Hub stores\n\n"
    + "The Hub stores reviewed knowledge, relationships, Questions, limitations, evidence "
    + "and small observed-value snapshots as linked Markdown concepts. It does not duplicate "
    + "repository source code or the private local Code Graph; concepts retain references that "
    + "help readers return to source evidence when more detail is needed.\n\n"
    + "## Layout\n\n"
    + "```text\n"
    + "index.md                 Knowledge entrypoint\n"
    + "domains/                 Domain knowledge\n"
    + "repositories/            Repository identity and evidence scope\n"
    + "systems/, components/    System and workload knowledge\n"
    + "interfaces/              Important integration boundaries\n"
    + "<other concept types>/   Added only when useful knowledge exists\n"
    + ".agentbase/ci/           Self-contained Hub validator\n"
    + ".github/workflows/       Read-only Hub CI\n"
    + "```\n\n"
    + "Category listings are generated presentation, not files maintainers must keep in sync. "
    + "Internal infrastructure stays in its owning runtime page unless it has independent "
    + "ownership, lifecycle or cross-boundary value.\n\n"
    + "## How knowledge changes\n\n"
    + "AgentBase-MCP reads an authorized repository, prepares a Local Draft, and opens a "
    + "reviewable pull request. Knowledge becomes Published only after a maintainer merges "
    + "that PR and MCP synchronizes the Hub. Conflicting evidence may remain visible rather "
    + "than being forced into one unsupported answer.\n\n"
    + "Hub CI checks structure, links, obvious sensitive content and freshness metadata. "
    + "Freshness is warning-only; it never rewrites knowledge automatically.\n";
}
