export const HUB_README_PATH = "README.md" as const;

export function renderHubReadme(): string {
  return "# AgentBase-Hub\n\n"
    + "AgentBase-Hub is a human-readable OKF knowledge repository created and managed by "
    + "AgentBase-MCP. "
    + "Return to this Hub's [repository root](.).\n\n"
    + "## Start here\n\n"
    + "Open [`index.md`](index.md). It is the canonical progressive-disclosure entrypoint "
    + "for both people and agents. Follow its direct Domain or Repository entrypoints, then "
    + "their links to useful concepts instead of scanning every file.\n\n"
    + "## What this Hub stores\n\n"
    + "The Hub stores reviewed knowledge, relationships, Questions, limitations, evidence "
    + "and small observed-value snapshots as linked Markdown concepts. It does not duplicate "
    + "repository source code or private discovery state; concepts retain references that "
    + "help readers return to source evidence when more detail is needed.\n\n"
    + "## Layout\n\n"
    + "```text\n"
    + "index.md                         Knowledge entrypoint\n"
    + "domains/<slug>/index.md          Domain concept and Capsule entrypoint\n"
    + "domains/<slug>/repositories/     Repository dossiers\n"
    + "domains/<slug>/knowledge/        Independently useful knowledge\n"
    + "domains/<slug>/questions/        Governed Domain Questions\n"
    + "shared/index.md                  Shared-knowledge entrypoint\n"
    + "shared/repositories/             Repositories without one honest Domain home\n"
    + "shared/knowledge/                Independently useful shared knowledge\n"
    + "shared/questions/                Governed shared Questions\n"
    + "shared/agentbase-profile.md      AgentBase OKF Profile declaration\n"
    + ".agentbase/ci/                   Self-contained Hub validator\n"
    + ".github/workflows/               Read-only Hub CI\n"
    + "```\n\n"
    + "A physical home controls placement and default navigation; only an evidenced "
    + "relationship expresses Domain participation. Collections are created only when useful "
    + "knowledge exists, and semantic type remains frontmatter rather than a directory name. "
    + "Internal infrastructure stays in its owning runtime page unless it has independent "
    + "ownership, lifecycle or cross-boundary value.\n\n"
    + "## How knowledge changes\n\n"
    + "AgentBase-MCP reads an authorized repository, prepares a Local Draft, and opens a "
    + "reviewable pull request. Knowledge becomes Published only after a maintainer merges "
    + "that PR and MCP synchronizes the Hub. Conflicting evidence may remain visible rather "
    + "than being forced into one unsupported answer.\n\n"
    + "Hub CI checks structure, links, obvious sensitive content and freshness metadata. "
    + "Freshness is warning-only; it never rewrites knowledge automatically.\n";
}
